-- ╔══════════════════════════════════════════════════════════════════╗
-- ║  Dedetech — F3: Funil Comercial / Pipeline + Orçamento            ║
-- ║  deals, deal_tasks, quotes, quote_items                           ║
-- ╚══════════════════════════════════════════════════════════════════╝

-- ─── Enums ───────────────────────────────────────────────────────────
create type deal_stage as enum (
  'lead','contato','diagnostico','orcamento','negociacao','ganho','perdido'
);
create type lead_origin as enum (
  'indicacao','google','instagram','site','passagem','outro'
);
create type loss_reason as enum (
  'preco','prazo','concorrente','sem_retorno','outro'
);
create type quote_status as enum (
  'rascunho','enviado','aceito','recusado','expirado'
);
create type quote_item_kind as enum ('servico','produto','outro');

-- ─── DEALS (cartões do pipeline) ─────────────────────────────────────
create table public.deals (
  id uuid primary key default uuid_generate_v4(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  client_id uuid references public.clients(id) on delete set null,
  -- dados do lead quando ainda não virou cliente
  nome_contato text not null,
  telefone text,
  email text,
  origem lead_origin not null default 'outro',
  stage deal_stage not null default 'lead',
  valor_estimado numeric not null default 0,
  owner_id uuid references auth.users(id) on delete set null,  -- vendedor
  descricao text,
  motivo_perda loss_reason,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index on public.deals (tenant_id);
create index on public.deals (tenant_id, stage);
create index on public.deals (client_id);

-- ─── DEAL TASKS (follow-ups) ─────────────────────────────────────────
create table public.deal_tasks (
  id uuid primary key default uuid_generate_v4(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  deal_id uuid not null references public.deals(id) on delete cascade,
  titulo text not null,
  due_at timestamptz,
  done boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index on public.deal_tasks (tenant_id);
create index on public.deal_tasks (deal_id);

-- ─── QUOTES (orçamento / proposta) ───────────────────────────────────
create table public.quotes (
  id uuid primary key default uuid_generate_v4(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  deal_id uuid not null references public.deals(id) on delete cascade,
  numero bigint generated by default as identity,
  status quote_status not null default 'rascunho',
  validade date,
  desconto numeric not null default 0,           -- valor absoluto (R$)
  observacoes text,
  public_token text not null unique default encode(gen_random_bytes(16),'hex'),
  enviado_em timestamptz,
  aceito_em timestamptz,
  recusado_em timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index on public.quotes (tenant_id);
create index on public.quotes (deal_id);
create index on public.quotes (public_token);

-- ─── QUOTE ITEMS ─────────────────────────────────────────────────────
create table public.quote_items (
  id uuid primary key default uuid_generate_v4(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  quote_id uuid not null references public.quotes(id) on delete cascade,
  kind quote_item_kind not null default 'servico',
  service_id uuid references public.services(id) on delete set null,
  product_id uuid references public.products(id) on delete set null,
  descricao text not null,
  quantidade numeric not null default 1,
  preco_unit numeric not null default 0,
  subtotal numeric generated always as (quantidade * preco_unit) stored,
  created_at timestamptz not null default now()
);
create index on public.quote_items (tenant_id);
create index on public.quote_items (quote_id);

-- ─── updated_at + auditoria + RLS ────────────────────────────────────
do $$
declare t text;
begin
  foreach t in array array['deals','deal_tasks','quotes','quote_items'] loop
    if t <> 'quote_items' then
      execute format(
        'create trigger t_%1$s_upd before update on public.%1$s
           for each row execute function public.set_updated_at();', t);
    end if;
    execute format(
      'create trigger t_%1$s_audit after insert or update or delete on public.%1$s
         for each row execute function public.audit_trigger();', t);
    execute format('alter table public.%1$s enable row level security;', t);
    execute format(
      'create policy %1$s_tenant on public.%1$s for all
         using (tenant_id = current_tenant_id())
         with check (tenant_id = current_tenant_id());', t);
  end loop;
end $$;
