-- ╔══════════════════════════════════════════════════════════════════╗
-- ║  Dedetech — F6: Ordens de Serviço + Ficha de Campo                ║
-- ║  service_orders + service_order_products                          ║
-- ╚══════════════════════════════════════════════════════════════════╝

create type os_status as enum (
  'agendada','a_caminho','em_execucao','executada','faturada','cancelada'
);
create type application_method as enum (
  'pulverizacao','polvilhamento','gel','isca','atomizacao',
  'termonebulizacao','injecao','outro'
);

-- ─── ORDENS DE SERVIÇO ───────────────────────────────────────────────
create table public.service_orders (
  id uuid primary key default uuid_generate_v4(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  numero bigint generated by default as identity,
  client_id uuid not null references public.clients(id) on delete restrict,
  unit_id uuid references public.client_units(id) on delete set null,
  -- origem (avulsa do orçamento ou recorrente do contrato)
  contract_id uuid references public.contracts(id) on delete set null,
  quote_id uuid references public.quotes(id) on delete set null,
  -- atribuição
  tecnico_id uuid references public.employees(id) on delete set null,
  vehicle_id uuid references public.vehicles(id) on delete set null,
  scheduled_at timestamptz,
  status os_status not null default 'agendada',
  -- execução / ficha de campo
  chegada_em timestamptz,
  saida_em timestamptz,
  lat numeric, lng numeric,
  pragas text[] not null default '{}',
  metodo application_method,
  metragem_m2 numeric,
  observacoes text,
  recomendacoes text,
  periodo_reentrada_horas int,
  garantia_meses int not null default 0,
  assinatura_cliente_url text,
  assinatura_tecnico_url text,
  proxima_revisao_em date,
  executada_em timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index on public.service_orders (tenant_id);
create index on public.service_orders (tenant_id, status);
create index on public.service_orders (tenant_id, scheduled_at);
create index on public.service_orders (client_id);
create index on public.service_orders (tecnico_id);
create index on public.service_orders (contract_id);

-- ─── PRODUTOS UTILIZADOS NA OS ───────────────────────────────────────
create table public.service_order_products (
  id uuid primary key default uuid_generate_v4(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  os_id uuid not null references public.service_orders(id) on delete cascade,
  product_id uuid not null references public.products(id) on delete restrict,
  batch_id uuid references public.stock_batches(id) on delete set null,
  quantidade numeric not null default 0,
  diluicao text,
  created_at timestamptz not null default now()
);
create index on public.service_order_products (tenant_id);
create index on public.service_order_products (os_id);

-- ─── updated_at + auditoria + RLS ────────────────────────────────────
create trigger t_service_orders_upd before update on public.service_orders
  for each row execute function public.set_updated_at();

do $$
declare t text;
begin
  foreach t in array array['service_orders','service_order_products'] loop
    execute format(
      'create trigger t_%1$s_audit after insert or update or delete on public.%1$s
         for each row execute function public.audit_trigger();', t);
    execute format('alter table public.%1$s enable row level security;', t);
    execute format(
      'create policy %1$s_tenant on public.%1$s for all
         using (tenant_id = current_tenant_id())
         with check (tenant_id = current_tenant_id());', t);
  end loop;
end $$;
